engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  fixme:
    enabled: true
exclude_paths:
  - spec/**/*
  - "**/vendor/**/*"